### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by jcarroll-mediafly** [orchely/ColorThiefSwift#4]
Hey there, I was wondering if there are plans to open up the podspec to include tvOS as well?

**Comment by yamoridon** [comment]
Hi jcarroll,

Though I have not tested at all because I don't have Apple TV, I made a branch and just added one line to podspec for supporting tvOS.
Could you try tvos branch?

Thank you,
Kazuki

**Comment by jcarroll-mediafly** [comment]
Thanks, will test it out!

**Comment by jcarroll-mediafly** [comment]
works for me!

**Comment by yamoridon** [comment]
Great!

**Comment by jcarroll-mediafly** [comment]
Thanks again for the quick turnaround. Can't wait to see cocoapods master updated. 

For anyone else who needs tvOS support you can do so by 

`pod 'ColorThiefSwift', :git => 'https://github.com/orchely/ColorThiefSwift.git'`

**Comment by yamoridon** [comment]
Though I haven't tested by myself, I merged to master.
